USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS DEVOPSDEMO_COMMON;

CREATE OR REPLACE API INTEGRATION git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/<insert GitHub username>') -- INSERT YOUR GITHUB USERNAME HERE
  ENABLED = TRUE;

CREATE OR REPLACE GIT REPOSITORY DEVOPSDEMO_COMMON.PUBLIC.DEVOPSDEMO
  API_INTEGRATION = git_api_integration
  ORIGIN = '<insert URL of your GitHub repo>'; 

CREATE USER IF NOT EXISTS DEVOPSDEMO
PASSWORD = 'pick a password here'
;

CREATE OR REPLACE DATABASE DEVOPSDEMO_PROD;
CREATE OR REPLACE DATABASE DEVOPSDEMO_DEV;

CREATE OR REPLACE ROLE DEVOPSDEMO;
GRANT ROLE DEVOPSDEMO TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEVOPSDEMO;

GRANT USAGE ON DATABASE DEVOPSDEMO_COMMON TO ROLE DEVOPSDEMO;
GRANT USAGE ON DATABASE DEVOPSDEMO_PROD TO ROLE DEVOPSDEMO;
GRANT USAGE ON DATABASE DEVOPSDEMO_DEV TO ROLE DEVOPSDEMO;

GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DEVOPSDEMO_COMMON TO ROLE DEVOPSDEMO;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DEVOPSDEMO_PROD TO ROLE DEVOPSDEMO;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DEVOPSDEMO_DEV TO ROLE DEVOPSDEMO;

CREATE SCHEMA IF NOT EXISTS DEVOPSDEMO_PROD.SALES;
CREATE SCHEMA IF NOT EXISTS DEVOPSDEMO_DEV.SALES;
GRANT ROLE DEVOPSDEMO TO USER DEVOPSDEMO;

USE ROLE DEVOPSDEMO;

